//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TInventory
    {
        public int Items_Id { get; set; }
        public string Items_number { get; set; }
        public Nullable<int> Colour { get; set; }
        public Nullable<double> Size { get; set; }
        public Nullable<double> Unit_Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public string Items_Name { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public bool is_deleted { get; set; }
        public Nullable<int> deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_date { get; set; }
        public Nullable<double> MarginPrice { get; set; }
    }
}
