//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJournal
    {
        public int TJournalID { get; set; }
        public string TransactionCode { get; set; }
        public int Account { get; set; }
        public string DebitCredit { get; set; }
        public double Amount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public bool is_deleted { get; set; }
        public Nullable<int> deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_date { get; set; }
    }
}
