//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRole
    {
        public int Role_id { get; set; }
        public bool is_Admin { get; set; }
        public string Role_Name { get; set; }
        public string ROle_Description { get; set; }
    }
}
