//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSafetyStock
    {
        public int Safetystock_id { get; set; }
        public int ItemsId { get; set; }
        public double SafetyStock { get; set; }
        public System.DateTime safetystockDateStart { get; set; }
        public System.DateTime safetystockDateEnd { get; set; }
        public int Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<int> Updated_by { get; set; }
    }
}
